//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessLevel
    {
        public int AccessLevelId { get; set; }
        public int RoleId { get; set; }
        public int FeatureId { get; set; }
        public System.DateTime InsertTime { get; set; }
        public int InsertUserId { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    
        public virtual Feature Feature { get; set; }
        public virtual Role Role { get; set; }
    }
}
