//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressComponent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AddressComponent()
        {
            this.AddressComponent1 = new HashSet<AddressComponent>();
            this.House = new HashSet<House>();
        }
    
        public int AddressComponentId { get; set; }
        public string AddressComponentName { get; set; }
        public string AddressComponentDesc { get; set; }
        public string AddressComponentZiped { get; set; }
        public int AddressComponentTypeId { get; set; }
        public int SegmentId { get; set; }
        public int ParentId { get; set; }
        public int InsertUserId { get; set; }
        public System.DateTime InsertTime { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AddressComponent> AddressComponent1 { get; set; }
        public virtual AddressComponent AddressComponent2 { get; set; }
        public virtual AddressComponentType AddressComponentType { get; set; }
        public virtual Segment Segment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<House> House { get; set; }
    }
}
