//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_اطلاعات_فرزندان_خانوارها__
    {
        public Nullable<int> GenderId { get; set; }
        public int Id { get; set; }
        public Nullable<double> شماره_فرم { get; set; }
        public Nullable<double> شماره_خانواده { get; set; }
        public Nullable<double> شماره_فرزند_ { get; set; }
        public string نام_ { get; set; }
        public string نام_خانوادگی { get; set; }
        public Nullable<double> سن { get; set; }
        public string میزان_تحصیلات { get; set; }
        public Nullable<double> آخرین_سال_تحصیلی { get; set; }
        public string آیا_ترک_تحصیل_کرده { get; set; }
        public Nullable<double> شماره_تماس { get; set; }
        public string دارنده_خط { get; set; }
        public string شماره_تماس2 { get; set; }
        public string دارنده_خط3 { get; set; }
        public string تحت_پوشش_جمعیت { get; set; }
        public string حمایت_تحصیلی_و_آموزشی { get; set; }
        public string حمایت_درمانی { get; set; }
        public string حمایت_فرهنگی { get; set; }
        public string مددکاری { get; set; }
        public string ملیت { get; set; }
        public string اوراق_هویت { get; set; }
        public string کارت_آبی_گرفته { get; set; }
        public string تاریخ_اعتبار { get; set; }
        public string کارت_واکسن { get; set; }
        public string آیا_کودک_کار_است { get; set; }
        public string شغل { get; set; }
        public string مهارت_و_استعداد_خاص { get; set; }
        public string علاقه_مندی { get; set; }
        public string بیماری_خاص { get; set; }
        public string توضیحات { get; set; }
        public string نیاز_به_پیگیری_دارد { get; set; }
        public string وضعیت_بهداشت_دندان { get; set; }
        public string توضیحات4 { get; set; }
        public string آدرس { get; set; }
        public string توضیحات2 { get; set; }
        public string F35 { get; set; }
        public string F36 { get; set; }
        public string F37 { get; set; }
        public string F38 { get; set; }
        public string F39 { get; set; }
        public string F40 { get; set; }
        public string F41 { get; set; }
        public string F42 { get; set; }
        public string F43 { get; set; }
        public string F44 { get; set; }
        public string F45 { get; set; }
        public string F46 { get; set; }
        public string F47 { get; set; }
    }
}
