//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompetitionSkillTypeAgeRange
    {
        public int CompetitionSkillTypeAgeRangeId { get; set; }
        public int SkillTypeAgeRangeId { get; set; }
        public int CompetitionId { get; set; }
        public string FromBirthDateSolar { get; set; }
        public Nullable<System.DateTime> FromBirthDate { get; set; }
        public string ToBirthDateSolar { get; set; }
        public Nullable<System.DateTime> ToBirthDate { get; set; }
        public int InsertUserId { get; set; }
        public System.DateTime InsertTime { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    
        public virtual Competition Competition { get; set; }
        public virtual SkillTypeAgeRange SkillTypeAgeRange { get; set; }
    }
}
