//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Competition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Competition()
        {
            this.CompetitionSkillTypeAgeRange = new HashSet<CompetitionSkillTypeAgeRange>();
            this.DepartmentTeamCompetition = new HashSet<DepartmentTeamCompetition>();
        }
    
        public int CompetitionId { get; set; }
        public string CompetitionName { get; set; }
        public string CompetitionSummaryName { get; set; }
        public string CompetitionZiped { get; set; }
        public string CompetitionStartDateSolar { get; set; }
        public System.DateTime CompetitionStartDate { get; set; }
        public int CompetitionDuration { get; set; }
        public int CompetitionTypeId { get; set; }
        public int InsertUserId { get; set; }
        public System.DateTime InsertTime { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    
        public virtual CompetitionType CompetitionType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompetitionSkillTypeAgeRange> CompetitionSkillTypeAgeRange { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartmentTeamCompetition> DepartmentTeamCompetition { get; set; }
    }
}
