//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartmentTeamGoods
    {
        public int DepartmentTeamGoodsId { get; set; }
        public int DepartmentTeamId { get; set; }
        public int GoodsId { get; set; }
        public double GoodsCount { get; set; }
        public int InsertUserId { get; set; }
        public System.DateTime InsertTime { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    
        public virtual DepartmentTeam DepartmentTeam { get; set; }
        public virtual Goods Goods { get; set; }
    }
}
