//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Department()
        {
            this.DepartmentAppliance = new HashSet<DepartmentAppliance>();
            this.DepartmentBank = new HashSet<DepartmentBank>();
            this.DepartmentBelive = new HashSet<DepartmentBelive>();
            this.DepartmentChildAbuseType = new HashSet<DepartmentChildAbuseType>();
            this.DepartmentChildMarriageCause = new HashSet<DepartmentChildMarriageCause>();
            this.DepartmentCrimeType = new HashSet<DepartmentCrimeType>();
            this.DepartmentDiedCause = new HashSet<DepartmentDiedCause>();
            this.DepartmentDisableType = new HashSet<DepartmentDisableType>();
            this.DepartmentDrugType = new HashSet<DepartmentDrugType>();
            this.DepartmentEducationField = new HashSet<DepartmentEducationField>();
            this.DepartmentEducationType = new HashSet<DepartmentEducationType>();
            this.DepartmentEthnic = new HashSet<DepartmentEthnic>();
            this.DepartmentFuelType = new HashSet<DepartmentFuelType>();
            this.DepartmentHouseBuildingMaterial = new HashSet<DepartmentHouseBuildingMaterial>();
            this.DepartmentInsuranceType = new HashSet<DepartmentInsuranceType>();
            this.DepartmentJob = new HashSet<DepartmentJob>();
            this.DepartmentLeavingHouseCause = new HashSet<DepartmentLeavingHouseCause>();
            this.DepartmentNationality = new HashSet<DepartmentNationality>();
            this.DepartmentPowerSupply = new HashSet<DepartmentPowerSupply>();
            this.DepartmentReferrer = new HashSet<DepartmentReferrer>();
            this.DepartmentRelationType = new HashSet<DepartmentRelationType>();
            this.DepartmentReligion = new HashSet<DepartmentReligion>();
            this.DepartmentResidenceType = new HashSet<DepartmentResidenceType>();
            this.DepartmentSegment = new HashSet<DepartmentSegment>();
            this.DepartmentSkillType = new HashSet<DepartmentSkillType>();
            this.DepartmentSupportingOrgan = new HashSet<DepartmentSupportingOrgan>();
            this.DepartmentTeam = new HashSet<DepartmentTeam>();
            this.DepartmentWaterSource = new HashSet<DepartmentWaterSource>();
            this.EducationYear = new HashSet<EducationYear>();
            this.Person = new HashSet<Person>();
            this.Personnel = new HashSet<Personnel>();
            this.Person1 = new HashSet<Person>();
            this.UserDepartment = new HashSet<UserDepartment>();
        }
    
        public int DepartmentId { get; set; }
        public string DepartmentCode { get; set; }
        public string DepartmentName { get; set; }
        public string DepartmentZiped { get; set; }
        public string DepartmentAddress { get; set; }
        public string DepartmentPostalCode { get; set; }
        public string DepartmentPhone1 { get; set; }
        public string DepartmentPhone2 { get; set; }
        public string DepartmentPhone3 { get; set; }
        public string DepartmentFax { get; set; }
        public Nullable<int> DepartmentRank { get; set; }
        public bool DepartmentIsActive { get; set; }
        public short DepartmentTypeId { get; set; }
        public int InsertUserId { get; set; }
        public System.DateTime InsertTime { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    
        public virtual DepartmentType DepartmentType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartmentAppliance> DepartmentAppliance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartmentBank> DepartmentBank { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartmentBelive> DepartmentBelive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartmentChildAbuseType> DepartmentChildAbuseType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartmentChildMarriageCause> DepartmentChildMarriageCause { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartmentCrimeType> DepartmentCrimeType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartmentDiedCause> DepartmentDiedCause { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartmentDisableType> DepartmentDisableType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartmentDrugType> DepartmentDrugType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartmentEducationField> DepartmentEducationField { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartmentEducationType> DepartmentEducationType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartmentEthnic> DepartmentEthnic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartmentFuelType> DepartmentFuelType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartmentHouseBuildingMaterial> DepartmentHouseBuildingMaterial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartmentInsuranceType> DepartmentInsuranceType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartmentJob> DepartmentJob { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartmentLeavingHouseCause> DepartmentLeavingHouseCause { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartmentNationality> DepartmentNationality { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartmentPowerSupply> DepartmentPowerSupply { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartmentReferrer> DepartmentReferrer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartmentRelationType> DepartmentRelationType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartmentReligion> DepartmentReligion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartmentResidenceType> DepartmentResidenceType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartmentSegment> DepartmentSegment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartmentSkillType> DepartmentSkillType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartmentSupportingOrgan> DepartmentSupportingOrgan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartmentTeam> DepartmentTeam { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartmentWaterSource> DepartmentWaterSource { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EducationYear> EducationYear { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Person> Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Personnel> Personnel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Person> Person1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserDepartment> UserDepartment { get; set; }
    }
}
