//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartmentTeamCompetitionDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DepartmentTeamCompetitionDetail()
        {
            this.PersonTeamGrade = new HashSet<PersonTeamGrade>();
        }
    
        public int DepartmentTeamCompetitionDetailId { get; set; }
        public int DepartmentTeamCompetitionId { get; set; }
        public string CompetitionStartTimeSolar { get; set; }
        public System.DateTime CompetitionStartTime { get; set; }
        public string CompetitionFinishTimeSolar { get; set; }
        public System.DateTime CompetitionFinishTime { get; set; }
        public string Place { get; set; }
        public string CompetitionDesc { get; set; }
        public string DepartmentTeamCompetitionDetailZiped { get; set; }
        public Nullable<int> OpponentTeamId { get; set; }
        public int CompetitionResultId { get; set; }
        public string CompetitionResultDesc { get; set; }
        public Nullable<int> DepartmentTeamPoints { get; set; }
        public Nullable<int> OpponentTeamPoints { get; set; }
        public Nullable<int> GradeId { get; set; }
        public int InsertUserId { get; set; }
        public System.DateTime InsertTime { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    
        public virtual DepartmentTeam DepartmentTeam { get; set; }
        public virtual DepartmentTeamCompetition DepartmentTeamCompetition { get; set; }
        public virtual Grade Grade { get; set; }
        public virtual Grade Grade1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonTeamGrade> PersonTeamGrade { get; set; }
    }
}
