//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartmentTeamExerciseHistory
    {
        public int DepartmentTeamExerciseHistoryId { get; set; }
        public Nullable<int> DepartmentTeamExerciseTimeId { get; set; }
        public int DepartmentTeamId { get; set; }
        public string ExerciseStartTimeSolar { get; set; }
        public System.DateTime ExerciseStartTime { get; set; }
        public string ExerciseFinishTimeSolar { get; set; }
        public System.DateTime ExerciseFinishTime { get; set; }
        public string Place { get; set; }
        public string ExerciseDesc { get; set; }
        public string DepartmentTeamExerciseTimeZiped { get; set; }
        public int InsertUserId { get; set; }
        public System.DateTime InsertTime { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    
        public virtual DepartmentTeam DepartmentTeam { get; set; }
        public virtual DepartmentTeamExerciseTime DepartmentTeamExerciseTime { get; set; }
    }
}
