//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartmentTeam
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DepartmentTeam()
        {
            this.DepartmentTeamCompetition = new HashSet<DepartmentTeamCompetition>();
            this.DepartmentTeamCompetitionDetail = new HashSet<DepartmentTeamCompetitionDetail>();
            this.DepartmentTeamExerciseHistory = new HashSet<DepartmentTeamExerciseHistory>();
            this.DepartmentTeamExerciseTime = new HashSet<DepartmentTeamExerciseTime>();
            this.DepartmentTeamGoods = new HashSet<DepartmentTeamGoods>();
            this.PersonTeam = new HashSet<PersonTeam>();
        }
    
        public int DepartmentTeamId { get; set; }
        public int DepartmentId { get; set; }
        public int TeamId { get; set; }
        public Nullable<System.DateTime> DepartmentTeamStartDate { get; set; }
        public string DepartmentTeamStartDateSolar1 { get; set; }
        public string DepartmentTeamDesc { get; set; }
        public string DepartmentTeamZiped { get; set; }
        public int InsertUserId { get; set; }
        public System.DateTime InsertTime { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Team Team { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartmentTeamCompetition> DepartmentTeamCompetition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartmentTeamCompetitionDetail> DepartmentTeamCompetitionDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartmentTeamExerciseHistory> DepartmentTeamExerciseHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartmentTeamExerciseTime> DepartmentTeamExerciseTime { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartmentTeamGoods> DepartmentTeamGoods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonTeam> PersonTeam { get; set; }
    }
}
