//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartmentTeamCompetition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DepartmentTeamCompetition()
        {
            this.DepartmentTeamCompetitionDetail = new HashSet<DepartmentTeamCompetitionDetail>();
            this.DepartmentTeamCompetitionMember = new HashSet<DepartmentTeamCompetitionMember>();
            this.PersonTeamGrade = new HashSet<PersonTeamGrade>();
        }
    
        public int DepartmentTeamCompetitionId { get; set; }
        public int CompetitionId { get; set; }
        public int DepartmentTeamId { get; set; }
        public string Place { get; set; }
        public string CompetitionDesc { get; set; }
        public string DepartmentTeamCompetitionZiped { get; set; }
        public Nullable<int> GradeId { get; set; }
        public string CompetitionResultDesc { get; set; }
        public int InsertUserId { get; set; }
        public System.DateTime InsertTime { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    
        public virtual Competition Competition { get; set; }
        public virtual DepartmentTeam DepartmentTeam { get; set; }
        public virtual Grade Grade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartmentTeamCompetitionDetail> DepartmentTeamCompetitionDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartmentTeamCompetitionMember> DepartmentTeamCompetitionMember { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonTeamGrade> PersonTeamGrade { get; set; }
    }
}
