//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartmentTeamExerciseTime
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DepartmentTeamExerciseTime()
        {
            this.DepartmentTeamExerciseHistory = new HashSet<DepartmentTeamExerciseHistory>();
        }
    
        public int DepartmentTeamExerciseTimeId { get; set; }
        public int DepartmentTeamId { get; set; }
        public int WeekDayId { get; set; }
        public string StartTime { get; set; }
        public string FinishTime { get; set; }
        public string Place { get; set; }
        public string DepartmentTeamExerciseTimeZiped { get; set; }
        public int InsertUserId { get; set; }
        public System.DateTime InsertTime { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    
        public virtual DepartmentTeam DepartmentTeam { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartmentTeamExerciseHistory> DepartmentTeamExerciseHistory { get; set; }
        public virtual WeekDay WeekDay { get; set; }
    }
}
