//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EducationYearClassMemberHistory
    {
        public int EducationYearClassMemberHistoryId { get; set; }
        public string EducationYearClassMemberHistoryDateSolar { get; set; }
        public System.DateTime EducationYearClassMemberHistoryDate { get; set; }
        public Nullable<int> EducationYearClassCourseTimeId { get; set; }
        public Nullable<int> AssessorId { get; set; }
        public Nullable<int> AssessorName { get; set; }
        public int EducationYearClassMemberId { get; set; }
        public Nullable<int> AssessmentModelId { get; set; }
        public Nullable<int> CourseAssessmentModelId { get; set; }
        public Nullable<int> AssessmentModelValueId { get; set; }
        public Nullable<double> AssessmentModelValue { get; set; }
        public string AssessmentModelDesc { get; set; }
        public string AssessmentModelZiped { get; set; }
        public int InsertUserId { get; set; }
        public System.DateTime InsertTime { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    
        public virtual AssessmentModel AssessmentModel { get; set; }
        public virtual AssessmentModelValue AssessmentModelValue1 { get; set; }
        public virtual CourseAssessmentModel CourseAssessmentModel { get; set; }
        public virtual EducationYearClassCourseTime EducationYearClassCourseTime { get; set; }
        public virtual EducationYearClassMember EducationYearClassMember { get; set; }
        public virtual Personnel Personnel { get; set; }
    }
}
