//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EducationYearClassCourseHistory
    {
        public int EducationYearClassCourseHistoryId { get; set; }
        public string EducationYearClassCourseHistoryCourseDesc { get; set; }
        public string EducationYearClassCourseHistoryClassTarget { get; set; }
        public string EducationYearClassCourseHistoryClassDesc { get; set; }
        public string EducationYearClassCourseHistoryClassPracticeDesc { get; set; }
        public string EducationYearClassCourseHistoryHomePracticeDesc { get; set; }
        public string EducationYearClassCourseHistoryRecommendation { get; set; }
        public string EducationYearClassCourseHistorySpecialDesc { get; set; }
        public string EducationYearClassCourseHistoryZiped { get; set; }
        public string EducationYearClassCourseHistoryDateSolar { get; set; }
        public System.DateTime EducationYearClassCourseHistoryDate { get; set; }
        public int EducationYearClassCourseTimeId { get; set; }
        public Nullable<int> SuccessorId { get; set; }
        public string SuccessorName { get; set; }
        public int InsertUserId { get; set; }
        public System.DateTime InsertTime { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    
        public virtual EducationYearClassCourseTime EducationYearClassCourseTime { get; set; }
        public virtual Personnel Personnel { get; set; }
    }
}
