//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EducationYearClass
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EducationYearClass()
        {
            this.EducationYearClassCourse = new HashSet<EducationYearClassCourse>();
            this.EducationYearClassMember = new HashSet<EducationYearClassMember>();
        }
    
        public int EducationYearClassId { get; set; }
        public string EducationYearClassName { get; set; }
        public string EducationYearClassSummeryName { get; set; }
        public string EducationYearClassDesc { get; set; }
        public string EducationYearClassZiped { get; set; }
        public int EducationYearId { get; set; }
        public int InsertUserId { get; set; }
        public System.DateTime InsertTime { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    
        public virtual EducationYear EducationYear { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EducationYearClassCourse> EducationYearClassCourse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EducationYearClassMember> EducationYearClassMember { get; set; }
    }
}
