//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacilityType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FacilityType()
        {
            this.PersonFacilityType = new HashSet<PersonFacilityType>();
        }
    
        public int FacilityTypeId { get; set; }
        public string FacilityTypeName { get; set; }
        public string FacilityTypeSummaryName { get; set; }
        public string FacilityTypeZiped { get; set; }
        public Nullable<bool> FacilityTypeIsCash { get; set; }
        public Nullable<int> FacilityCategoryId { get; set; }
        public int InsertUserId { get; set; }
        public System.DateTime InsertTime { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public System.DateTime ChangeTime { get; set; }
    
        public virtual FacilityCategory FacilityCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonFacilityType> PersonFacilityType { get; set; }
    }
}
