//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FamilyReconnaissance
    {
        public int FamilyReconnaissanceId { get; set; }
        public int FamilyId { get; set; }
        public string FamilyReconnaissanceDateSolar { get; set; }
        public System.DateTime FamilyReconnaissanceDate { get; set; }
        public string FamilyReconnaissanceDesc { get; set; }
        public string FamilyReconnaissanceZiped { get; set; }
        public Nullable<int> ReconnaissanceCauseId { get; set; }
        public int InsertUserId { get; set; }
        public System.DateTime InsertTime { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    
        public virtual Family Family { get; set; }
        public virtual ReconnaissanceCause ReconnaissanceCause { get; set; }
    }
}
