//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feature
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Feature()
        {
            this.AccessLevel = new HashSet<AccessLevel>();
        }
    
        public int FeatureId { get; set; }
        public string FeatureName { get; set; }
        public string FeatureZiped { get; set; }
        public bool FeatureIsActive { get; set; }
        public int FeatureTypeId { get; set; }
        public int SubSystemId { get; set; }
        public Nullable<int> TargetSubSystemId { get; set; }
        public int InsertUserId { get; set; }
        public System.DateTime InsertTime { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccessLevel> AccessLevel { get; set; }
        public virtual SubSystem SubSystem { get; set; }
        public virtual SubSystem SubSystem1 { get; set; }
        public virtual FeatureType FeatureType { get; set; }
    }
}
