//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grade
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Grade()
        {
            this.DepartmentTeamCompetition = new HashSet<DepartmentTeamCompetition>();
            this.DepartmentTeamCompetitionDetail = new HashSet<DepartmentTeamCompetitionDetail>();
            this.DepartmentTeamCompetitionDetail1 = new HashSet<DepartmentTeamCompetitionDetail>();
            this.PersonTeamGrade = new HashSet<PersonTeamGrade>();
        }
    
        public int GradeId { get; set; }
        public int SkillTypeId { get; set; }
        public Nullable<int> GradePoints { get; set; }
        public string GradeName { get; set; }
        public string GradeZiped { get; set; }
        public bool PersonRelated { get; set; }
        public bool TeamRelated { get; set; }
        public int InsertUserId { get; set; }
        public System.DateTime InsertTime { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartmentTeamCompetition> DepartmentTeamCompetition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartmentTeamCompetitionDetail> DepartmentTeamCompetitionDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartmentTeamCompetitionDetail> DepartmentTeamCompetitionDetail1 { get; set; }
        public virtual SkillType SkillType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonTeamGrade> PersonTeamGrade { get; set; }
    }
}
