//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HousePhone
    {
        public int HousePhoneId { get; set; }
        public int HouseId { get; set; }
        public string Phone { get; set; }
        public string HousePhoneDesc { get; set; }
        public string HousePhoneZiped { get; set; }
        public Nullable<int> PersonId { get; set; }
        public int InsertUserId { get; set; }
        public System.DateTime InsertTime { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    }
}
