//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IASDataEntities : DbContext
    {
        public IASDataEntities()
            : base("name=IASDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccessLevel> AccessLevel { get; set; }
        public virtual DbSet<ActivityField> ActivityField { get; set; }
        public virtual DbSet<ActivityType> ActivityType { get; set; }
        public virtual DbSet<AddressComponent> AddressComponent { get; set; }
        public virtual DbSet<AddressComponentType> AddressComponentType { get; set; }
        public virtual DbSet<Alley> Alley { get; set; }
        public virtual DbSet<Appliance> Appliance { get; set; }
        public virtual DbSet<AssessmentModel> AssessmentModel { get; set; }
        public virtual DbSet<AssessmentModelCategory> AssessmentModelCategory { get; set; }
        public virtual DbSet<AssessmentModelValue> AssessmentModelValue { get; set; }
        public virtual DbSet<Bank> Bank { get; set; }
        public virtual DbSet<BaseInfo> BaseInfo { get; set; }
        public virtual DbSet<BaseInfoGroup> BaseInfoGroup { get; set; }
        public virtual DbSet<Belive> Belive { get; set; }
        public virtual DbSet<BeltColor> BeltColor { get; set; }
        public virtual DbSet<BloodType> BloodType { get; set; }
        public virtual DbSet<ChildAbuseType> ChildAbuseType { get; set; }
        public virtual DbSet<ChildMarriageCause> ChildMarriageCause { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Color> Color { get; set; }
        public virtual DbSet<Competition> Competition { get; set; }
        public virtual DbSet<CompetitionMemberStatus> CompetitionMemberStatus { get; set; }
        public virtual DbSet<CompetitionSkillTypeAgeRange> CompetitionSkillTypeAgeRange { get; set; }
        public virtual DbSet<CompetitionType> CompetitionType { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Course> Course { get; set; }
        public virtual DbSet<CourseAssessmentModel> CourseAssessmentModel { get; set; }
        public virtual DbSet<CrimeType> CrimeType { get; set; }
        public virtual DbSet<DamageCause> DamageCause { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<DepartmentAppliance> DepartmentAppliance { get; set; }
        public virtual DbSet<DepartmentBank> DepartmentBank { get; set; }
        public virtual DbSet<DepartmentBelive> DepartmentBelive { get; set; }
        public virtual DbSet<DepartmentChildAbuseType> DepartmentChildAbuseType { get; set; }
        public virtual DbSet<DepartmentChildMarriageCause> DepartmentChildMarriageCause { get; set; }
        public virtual DbSet<DepartmentCrimeType> DepartmentCrimeType { get; set; }
        public virtual DbSet<DepartmentDiedCause> DepartmentDiedCause { get; set; }
        public virtual DbSet<DepartmentDisableType> DepartmentDisableType { get; set; }
        public virtual DbSet<DepartmentDrugType> DepartmentDrugType { get; set; }
        public virtual DbSet<DepartmentEducationField> DepartmentEducationField { get; set; }
        public virtual DbSet<DepartmentEducationType> DepartmentEducationType { get; set; }
        public virtual DbSet<DepartmentEthnic> DepartmentEthnic { get; set; }
        public virtual DbSet<DepartmentFuelType> DepartmentFuelType { get; set; }
        public virtual DbSet<DepartmentHouseBuildingMaterial> DepartmentHouseBuildingMaterial { get; set; }
        public virtual DbSet<DepartmentInsuranceType> DepartmentInsuranceType { get; set; }
        public virtual DbSet<DepartmentJob> DepartmentJob { get; set; }
        public virtual DbSet<DepartmentLeavingHouseCause> DepartmentLeavingHouseCause { get; set; }
        public virtual DbSet<DepartmentNationality> DepartmentNationality { get; set; }
        public virtual DbSet<DepartmentPowerSupply> DepartmentPowerSupply { get; set; }
        public virtual DbSet<DepartmentReferrer> DepartmentReferrer { get; set; }
        public virtual DbSet<DepartmentRelationType> DepartmentRelationType { get; set; }
        public virtual DbSet<DepartmentReligion> DepartmentReligion { get; set; }
        public virtual DbSet<DepartmentResidenceType> DepartmentResidenceType { get; set; }
        public virtual DbSet<DepartmentSegment> DepartmentSegment { get; set; }
        public virtual DbSet<DepartmentSkillType> DepartmentSkillType { get; set; }
        public virtual DbSet<DepartmentSupportingOrgan> DepartmentSupportingOrgan { get; set; }
        public virtual DbSet<DepartmentTeam> DepartmentTeam { get; set; }
        public virtual DbSet<DepartmentTeamCompetition> DepartmentTeamCompetition { get; set; }
        public virtual DbSet<DepartmentTeamCompetitionDetail> DepartmentTeamCompetitionDetail { get; set; }
        public virtual DbSet<DepartmentTeamCompetitionMember> DepartmentTeamCompetitionMember { get; set; }
        public virtual DbSet<DepartmentTeamExerciseHistory> DepartmentTeamExerciseHistory { get; set; }
        public virtual DbSet<DepartmentTeamExerciseTime> DepartmentTeamExerciseTime { get; set; }
        public virtual DbSet<DepartmentTeamGoods> DepartmentTeamGoods { get; set; }
        public virtual DbSet<DepartmentType> DepartmentType { get; set; }
        public virtual DbSet<DepartmentWaterSource> DepartmentWaterSource { get; set; }
        public virtual DbSet<DiedCause> DiedCause { get; set; }
        public virtual DbSet<DisableType> DisableType { get; set; }
        public virtual DbSet<DrugHistory> DrugHistory { get; set; }
        public virtual DbSet<DrugStatus> DrugStatus { get; set; }
        public virtual DbSet<DrugType> DrugType { get; set; }
        public virtual DbSet<DrugWithdrawalHistory> DrugWithdrawalHistory { get; set; }
        public virtual DbSet<EducationField> EducationField { get; set; }
        public virtual DbSet<EducationStatus> EducationStatus { get; set; }
        public virtual DbSet<EducationType> EducationType { get; set; }
        public virtual DbSet<EducationYear> EducationYear { get; set; }
        public virtual DbSet<EducationYearClass> EducationYearClass { get; set; }
        public virtual DbSet<EducationYearClassCourse> EducationYearClassCourse { get; set; }
        public virtual DbSet<EducationYearClassCourseHistory> EducationYearClassCourseHistory { get; set; }
        public virtual DbSet<EducationYearClassCourseTime> EducationYearClassCourseTime { get; set; }
        public virtual DbSet<EducationYearClassMember> EducationYearClassMember { get; set; }
        public virtual DbSet<EducationYearClassMemberHistory> EducationYearClassMemberHistory { get; set; }
        public virtual DbSet<EquipmentType> EquipmentType { get; set; }
        public virtual DbSet<Ethnic> Ethnic { get; set; }
        public virtual DbSet<ExpenseType> ExpenseType { get; set; }
        public virtual DbSet<Expertise> Expertise { get; set; }
        public virtual DbSet<ExpireCause> ExpireCause { get; set; }
        public virtual DbSet<FacilityCategory> FacilityCategory { get; set; }
        public virtual DbSet<FacilityType> FacilityType { get; set; }
        public virtual DbSet<Family> Family { get; set; }
        public virtual DbSet<FamilyAppliance> FamilyAppliance { get; set; }
        public virtual DbSet<FamilyLog> FamilyLog { get; set; }
        public virtual DbSet<FamilyMember> FamilyMember { get; set; }
        public virtual DbSet<FamilyPhone> FamilyPhone { get; set; }
        public virtual DbSet<FamilyStatus> FamilyStatus { get; set; }
        public virtual DbSet<Feature> Feature { get; set; }
        public virtual DbSet<FeatureType> FeatureType { get; set; }
        public virtual DbSet<FuelType> FuelType { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<Goods> Goods { get; set; }
        public virtual DbSet<GoodsCategory> GoodsCategory { get; set; }
        public virtual DbSet<GoodsType> GoodsType { get; set; }
        public virtual DbSet<Grade> Grade { get; set; }
        public virtual DbSet<HealthType> HealthType { get; set; }
        public virtual DbSet<House> House { get; set; }
        public virtual DbSet<HouseAppliance> HouseAppliance { get; set; }
        public virtual DbSet<HouseBuildingMaterial> HouseBuildingMaterial { get; set; }
        public virtual DbSet<HouseFamily> HouseFamily { get; set; }
        public virtual DbSet<HousePhone> HousePhone { get; set; }
        public virtual DbSet<HouseStatus> HouseStatus { get; set; }
        public virtual DbSet<HouseType> HouseType { get; set; }
        public virtual DbSet<HttpLog> HttpLog { get; set; }
        public virtual DbSet<IdentityDocument> IdentityDocument { get; set; }
        public virtual DbSet<IncomeType> IncomeType { get; set; }
        public virtual DbSet<InsuranceType> InsuranceType { get; set; }
        public virtual DbSet<Job> Job { get; set; }
        public virtual DbSet<JobStatus> JobStatus { get; set; }
        public virtual DbSet<LeavingHouseCause> LeavingHouseCause { get; set; }
        public virtual DbSet<Limb> Limb { get; set; }
        public virtual DbSet<MaritalStatus> MaritalStatus { get; set; }
        public virtual DbSet<MigrationCause> MigrationCause { get; set; }
        public virtual DbSet<Nationality> Nationality { get; set; }
        public virtual DbSet<NeedType> NeedType { get; set; }
        public virtual DbSet<Person> Person { get; set; }
        public virtual DbSet<PersonChildAbuseType> PersonChildAbuseType { get; set; }
        public virtual DbSet<PersonCrimeType> PersonCrimeType { get; set; }
        public virtual DbSet<PersonDamage> PersonDamage { get; set; }
        public virtual DbSet<PersonDentalMonitoring> PersonDentalMonitoring { get; set; }
        public virtual DbSet<PersonDisableType> PersonDisableType { get; set; }
        public virtual DbSet<PersonDrugType> PersonDrugType { get; set; }
        public virtual DbSet<PersonExpense> PersonExpense { get; set; }
        public virtual DbSet<PersonFacilityType> PersonFacilityType { get; set; }
        public virtual DbSet<PersonIdentityDocument> PersonIdentityDocument { get; set; }
        public virtual DbSet<PersonIncome> PersonIncome { get; set; }
        public virtual DbSet<PersonInsuranceType> PersonInsuranceType { get; set; }
        public virtual DbSet<PersonJob> PersonJob { get; set; }
        public virtual DbSet<PersonLog> PersonLog { get; set; }
        public virtual DbSet<PersonMedicalMonitoring> PersonMedicalMonitoring { get; set; }
        public virtual DbSet<PersonNeedType> PersonNeedType { get; set; }
        public virtual DbSet<Personnel> Personnel { get; set; }
        public virtual DbSet<PersonnelActivityField> PersonnelActivityField { get; set; }
        public virtual DbSet<PersonnelCourse> PersonnelCourse { get; set; }
        public virtual DbSet<PersonnelFreeDay> PersonnelFreeDay { get; set; }
        public virtual DbSet<PersonnelLog> PersonnelLog { get; set; }
        public virtual DbSet<PersonnelPursuit> PersonnelPursuit { get; set; }
        public virtual DbSet<PersonnelPursuitResult> PersonnelPursuitResult { get; set; }
        public virtual DbSet<PersonnelSkillType> PersonnelSkillType { get; set; }
        public virtual DbSet<PersonnelStatus> PersonnelStatus { get; set; }
        public virtual DbSet<PersonnelWorkshop> PersonnelWorkshop { get; set; }
        public virtual DbSet<PersonNew> PersonNew { get; set; }
        public virtual DbSet<PersonSicknessType> PersonSicknessType { get; set; }
        public virtual DbSet<PersonSkillType> PersonSkillType { get; set; }
        public virtual DbSet<PersonStatus> PersonStatus { get; set; }
        public virtual DbSet<PersonSupportingOrgan> PersonSupportingOrgan { get; set; }
        public virtual DbSet<PersonSupportingOrganServiceType> PersonSupportingOrganServiceType { get; set; }
        public virtual DbSet<PersonTalent> PersonTalent { get; set; }
        public virtual DbSet<PersonTeam> PersonTeam { get; set; }
        public virtual DbSet<PersonTeamGrade> PersonTeamGrade { get; set; }
        public virtual DbSet<PersonToothStatus> PersonToothStatus { get; set; }
        public virtual DbSet<PersonTraningCourseType> PersonTraningCourseType { get; set; }
        public virtual DbSet<PersonWorkshop> PersonWorkshop { get; set; }
        public virtual DbSet<PlaceCategory> PlaceCategory { get; set; }
        public virtual DbSet<PlaceType> PlaceType { get; set; }
        public virtual DbSet<PowerSupply> PowerSupply { get; set; }
        public virtual DbSet<Province> Province { get; set; }
        public virtual DbSet<PunishmentCheckOutCause> PunishmentCheckOutCause { get; set; }
        public virtual DbSet<PunishmentClass> PunishmentClass { get; set; }
        public virtual DbSet<PunishmentStatus> PunishmentStatus { get; set; }
        public virtual DbSet<PunishmentType> PunishmentType { get; set; }
        public virtual DbSet<ReconnaissanceCause> ReconnaissanceCause { get; set; }
        public virtual DbSet<Referrer> Referrer { get; set; }
        public virtual DbSet<Region> Region { get; set; }
        public virtual DbSet<RelationType> RelationType { get; set; }
        public virtual DbSet<Religion> Religion { get; set; }
        public virtual DbSet<ResidenceType> ResidenceType { get; set; }
        public virtual DbSet<ResidentialContext> ResidentialContext { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<RoleMember> RoleMember { get; set; }
        public virtual DbSet<RoleMemberAccess> RoleMemberAccess { get; set; }
        public virtual DbSet<Segment> Segment { get; set; }
        public virtual DbSet<SegmentDrugType> SegmentDrugType { get; set; }
        public virtual DbSet<SegmentEthnic> SegmentEthnic { get; set; }
        public virtual DbSet<SegmentFuelType> SegmentFuelType { get; set; }
        public virtual DbSet<SegmentPlaceType> SegmentPlaceType { get; set; }
        public virtual DbSet<SegmentReconnaissance> SegmentReconnaissance { get; set; }
        public virtual DbSet<SegmentReconnaissanceDrugType> SegmentReconnaissanceDrugType { get; set; }
        public virtual DbSet<SegmentReconnaissanceEthnic> SegmentReconnaissanceEthnic { get; set; }
        public virtual DbSet<SegmentReconnaissanceFuelType> SegmentReconnaissanceFuelType { get; set; }
        public virtual DbSet<SegmentReconnaissancePlaceType> SegmentReconnaissancePlaceType { get; set; }
        public virtual DbSet<SegmentReconnaissanceResidentialContext> SegmentReconnaissanceResidentialContext { get; set; }
        public virtual DbSet<SegmentReconnaissanceWaterSource> SegmentReconnaissanceWaterSource { get; set; }
        public virtual DbSet<SegmentResidentialContext> SegmentResidentialContext { get; set; }
        public virtual DbSet<SegmentWaterSource> SegmentWaterSource { get; set; }
        public virtual DbSet<ServiceType> ServiceType { get; set; }
        public virtual DbSet<SicknessType> SicknessType { get; set; }
        public virtual DbSet<SkillType> SkillType { get; set; }
        public virtual DbSet<SkillTypeAgeRange> SkillTypeAgeRange { get; set; }
        public virtual DbSet<SkillTypeLevel> SkillTypeLevel { get; set; }
        public virtual DbSet<Street> Street { get; set; }
        public virtual DbSet<SubSystem> SubSystem { get; set; }
        public virtual DbSet<SupportingOrgan> SupportingOrgan { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tbl_Cities> tbl_Cities { get; set; }
        public virtual DbSet<tbl_Counties> tbl_Counties { get; set; }
        public virtual DbSet<tbl_Provinces> tbl_Provinces { get; set; }
        public virtual DbSet<tbl_Villages> tbl_Villages { get; set; }
        public virtual DbSet<tbl_Zones> tbl_Zones { get; set; }
        public virtual DbSet<Team> Team { get; set; }
        public virtual DbSet<TeamRequiredGoods> TeamRequiredGoods { get; set; }
        public virtual DbSet<Tooth> Tooth { get; set; }
        public virtual DbSet<ToothStatus> ToothStatus { get; set; }
        public virtual DbSet<ToothType> ToothType { get; set; }
        public virtual DbSet<TradingType> TradingType { get; set; }
        public virtual DbSet<TraningCourseType> TraningCourseType { get; set; }
        public virtual DbSet<TreatmentStatus> TreatmentStatus { get; set; }
        public virtual DbSet<UserDepartment> UserDepartment { get; set; }
        public virtual DbSet<UserInfo> UserInfo { get; set; }
        public virtual DbSet<WaterSource> WaterSource { get; set; }
        public virtual DbSet<WeekDay> WeekDay { get; set; }
        public virtual DbSet<Workshop> Workshop { get; set; }
        public virtual DbSet<Workspace> Workspace { get; set; }
        public virtual DbSet<C_اطلاعات_فرزندان_خانوارها__> C_اطلاعات_فرزندان_خانوارها__ { get; set; }
        public virtual DbSet<BankHistory> BankHistory { get; set; }
        public virtual DbSet<BaseInfoHistory> BaseInfoHistory { get; set; }
        public virtual DbSet<DepartmentTeamCompetitionMemberHistory> DepartmentTeamCompetitionMemberHistory { get; set; }
        public virtual DbSet<EmployeeHistory> EmployeeHistory { get; set; }
        public virtual DbSet<FamilyHistory> FamilyHistory { get; set; }
        public virtual DbSet<FamilyMemberHistory> FamilyMemberHistory { get; set; }
        public virtual DbSet<FamilyReconnaissance> FamilyReconnaissance { get; set; }
        public virtual DbSet<PersonHistory> PersonHistory { get; set; }
        public virtual DbSet<UserDepartmentHistory> UserDepartmentHistory { get; set; }
        public virtual DbSet<UserInfoHistory> UserInfoHistory { get; set; }
    }
}
