//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonDrugType
    {
        public int PersonDrugTypeId { get; set; }
        public int PersonId { get; set; }
        public int DrugTypeId { get; set; }
        public Nullable<int> PersonDrugTypeDuration { get; set; }
        public string DrugStartYear { get; set; }
        public string DrugStartCause { get; set; }
        public string DrugDesc { get; set; }
        public string DrugStopYear { get; set; }
        public string DrugStopCause { get; set; }
        public int InsertUserId { get; set; }
        public System.DateTime InsertTime { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    
        public virtual DrugType DrugType { get; set; }
        public virtual Person Person { get; set; }
    }
}
