//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonIdentityDocument
    {
        public int PersonIdentityDocumentId { get; set; }
        public int PersonId { get; set; }
        public int IdentityDocumentId { get; set; }
        public string IdentityDocumentCode { get; set; }
        public string IdentityDocumentSerialNo { get; set; }
        public string PersonIdentityDocumentDesc { get; set; }
        public string IdentityDocumentPic { get; set; }
        public Nullable<System.DateTime> ExpireTime { get; set; }
        public string ExpireTimeSolar { get; set; }
        public string PersonIdentityDocumenZiped { get; set; }
        public int InsertUserId { get; set; }
        public System.DateTime InsertTime { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    
        public virtual IdentityDocument IdentityDocument { get; set; }
        public virtual Person Person { get; set; }
    }
}
