//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonSupportingOrgan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PersonSupportingOrgan()
        {
            this.PersonSupportingOrganServiceType = new HashSet<PersonSupportingOrganServiceType>();
        }
    
        public int PersonSupportingOrganId { get; set; }
        public int PersonId { get; set; }
        public int SupportingOrganId { get; set; }
        public string SupportingOrganName { get; set; }
        public Nullable<double> SupportingDuration { get; set; }
        public string SupportingCause { get; set; }
        public string SupportingDesc { get; set; }
        public string SupportingZiped { get; set; }
        public int InsertUserId { get; set; }
        public System.DateTime InsertTime { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual SupportingOrgan SupportingOrgan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonSupportingOrganServiceType> PersonSupportingOrganServiceType { get; set; }
    }
}
