//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonCrimeType
    {
        public int PersonCrimeTypeId { get; set; }
        public int PersonId { get; set; }
        public int CrimeTypeId { get; set; }
        public int PunishmentStatusId { get; set; }
        public int PunishmentTypeId { get; set; }
        public string PunishmentTypeDesc { get; set; }
        public string PunishmentStartTimeSolar { get; set; }
        public Nullable<System.DateTime> PunishmentStartTime { get; set; }
        public string PunishmentFinishTimeSolar { get; set; }
        public Nullable<System.DateTime> PunishmentFinishTime { get; set; }
        public Nullable<int> PunishmentCheckOutCauseId { get; set; }
        public string PunishmentCheckOutTimeSolar { get; set; }
        public Nullable<System.DateTime> PunishmentCheckOutTime { get; set; }
        public string PersonCrimeTypeDesc { get; set; }
        public string PersonCrimeTypeZiped { get; set; }
        public int InsertUserId { get; set; }
        public System.DateTime InsertTime { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    
        public virtual CrimeType CrimeType { get; set; }
        public virtual Person Person { get; set; }
        public virtual PunishmentCheckOutCause PunishmentCheckOutCause { get; set; }
        public virtual PunishmentStatus PunishmentStatus { get; set; }
        public virtual PunishmentType PunishmentType { get; set; }
    }
}
