//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonTeam
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PersonTeam()
        {
            this.PersonTeamGrade = new HashSet<PersonTeamGrade>();
            this.PersonTeamGrade1 = new HashSet<PersonTeamGrade>();
        }
    
        public int PersonTeamId { get; set; }
        public int PersonId { get; set; }
        public int DepartmentTeamId { get; set; }
        public Nullable<System.DateTime> PersonEnterToTeamDate { get; set; }
        public string PersonEnterToTeamDateSolar { get; set; }
        public Nullable<System.DateTime> PersonExitFromTeamDate { get; set; }
        public string PersonExitFromTeamDateSolar { get; set; }
        public string PersonExitFromTeamCause { get; set; }
        public string PersonTeamDesc { get; set; }
        public string PersonTeamZiped { get; set; }
        public bool IsCaptain { get; set; }
        public Nullable<int> ShirtNo { get; set; }
        public Nullable<int> ExpertiseId { get; set; }
        public Nullable<int> BeltColorId { get; set; }
        public int InsertUserId { get; set; }
        public System.DateTime InsertTime { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    
        public virtual BeltColor BeltColor { get; set; }
        public virtual DepartmentTeam DepartmentTeam { get; set; }
        public virtual Expertise Expertise { get; set; }
        public virtual Person Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonTeamGrade> PersonTeamGrade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonTeamGrade> PersonTeamGrade1 { get; set; }
    }
}
