//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonMedicalMonitoring
    {
        public int PersonMedicalMonitoringId { get; set; }
        public System.DateTime PersonMedicalMonitoringDate { get; set; }
        public string PersonMedicalMonitoringDateSolar { get; set; }
        public int PersonId { get; set; }
        public Nullable<double> PersonHeight { get; set; }
        public Nullable<double> PersonWeight { get; set; }
        public Nullable<double> BloodPressure_Systolic { get; set; }
        public Nullable<double> BloodPressure_Diastolic { get; set; }
        public Nullable<double> HeadCircumference { get; set; }
        public Nullable<double> AxillaryTemperature { get; set; }
        public Nullable<double> OralTemperature { get; set; }
        public int InsertUserId { get; set; }
        public System.DateTime InsertTime { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
