//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonChildAbuseType
    {
        public int PersonChildAbuseTypeId { get; set; }
        public int PersonId { get; set; }
        public int ChildAbuseTypeId { get; set; }
        public string PersonChildAbuseTypeDesc { get; set; }
        public string PersonChildAbuseTypeZiped { get; set; }
        public Nullable<int> RelationTypeId { get; set; }
        public string AbuserName { get; set; }
        public int InsertUserId { get; set; }
        public System.DateTime InsertTime { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    
        public virtual ChildAbuseType ChildAbuseType { get; set; }
        public virtual Person Person { get; set; }
        public virtual RelationType RelationType { get; set; }
    }
}
