//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonDisableType
    {
        public int PersonDisableTypeId { get; set; }
        public int PersonId { get; set; }
        public int DisableTypeId { get; set; }
        public string PersonDisableTypeDesc { get; set; }
        public string PersonDisableTypeZiped { get; set; }
        public int InsertUserId { get; set; }
        public System.DateTime InsertTime { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    
        public virtual DisableType DisableType { get; set; }
        public virtual Person Person { get; set; }
    }
}
