//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonnelSkillType
    {
        public int PersonnelSkillTypeId { get; set; }
        public int PersonnelId { get; set; }
        public int SkillTypeId { get; set; }
        public int SkillTypeLevelId { get; set; }
        public string BeltColor { get; set; }
        public Nullable<int> ShirtNo { get; set; }
        public Nullable<int> Duration { get; set; }
        public string PersonnelSkillTypeDesc { get; set; }
        public string PersonnelSkillTypeExpertise { get; set; }
        public int InsertUserId { get; set; }
        public System.DateTime InsertTime { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    
        public virtual Personnel Personnel { get; set; }
        public virtual SkillType SkillType { get; set; }
        public virtual SkillTypeLevel SkillTypeLevel { get; set; }
    }
}
