//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonTraningCourseType
    {
        public int PersonTraningCourseTypeId { get; set; }
        public int PersonId { get; set; }
        public int TraningCourseTypeId { get; set; }
        public string PersonTraningCourseTypeDateSolar { get; set; }
        public System.DateTime PersonTraningCourseTypeDate { get; set; }
        public string PersonTraningCourseTypeDesc { get; set; }
        public string PersonTraningCourseTypeZiped { get; set; }
        public int InsertUserId { get; set; }
        public System.DateTime InsertTime { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual TraningCourseType TraningCourseType { get; set; }
    }
}
