//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonToothStatus
    {
        public int PersonToothStatusId { get; set; }
        public int PersonDentalMonitoringId { get; set; }
        public short ToothId { get; set; }
        public int ToothStatusId { get; set; }
        public string PersonToothStatusDesc { get; set; }
        public string PersonToothStatusZiped { get; set; }
        public int InsertUserId { get; set; }
        public System.DateTime InsertTime { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    
        public virtual PersonDentalMonitoring PersonDentalMonitoring { get; set; }
        public virtual Tooth Tooth { get; set; }
        public virtual ToothStatus ToothStatus { get; set; }
    }
}
