//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonTalent
    {
        public int PersonTalentId { get; set; }
        public string PersonTalentDateSolar { get; set; }
        public System.DateTime PersonTalentDate { get; set; }
        public Nullable<int> SitUpPerMinute { get; set; }
        public Nullable<int> PushUpPerMinute { get; set; }
        public Nullable<double> SprintCooperRecord { get; set; }
        public Nullable<double> Sprint100MRecord { get; set; }
        public Nullable<double> Sprint200MRecord { get; set; }
        public Nullable<double> Sprint540MRecord { get; set; }
        public Nullable<double> Sprint2000MRecord { get; set; }
        public Nullable<double> SargentJumpRecord { get; set; }
        public Nullable<double> LongJumpRecord { get; set; }
        public string SpecialSkills { get; set; }
        public bool FootballSuitable { get; set; }
        public bool VolleyballSuitable { get; set; }
        public bool BasketballSuitable { get; set; }
        public bool SprintSuitable { get; set; }
        public bool MartialSuitable { get; set; }
        public string OtherSuitableSports { get; set; }
        public string FavoriteSports { get; set; }
        public string PersonTalentZiped { get; set; }
        public int PersonId { get; set; }
        public int InsertUserId { get; set; }
        public System.DateTime InsertTime { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
