//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonDentalMonitoring
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PersonDentalMonitoring()
        {
            this.PersonToothStatus = new HashSet<PersonToothStatus>();
        }
    
        public int PersonDentalMonitoringId { get; set; }
        public System.DateTime PersonDentalMonitoringDate { get; set; }
        public string PersonDentalMonitoringDateSolar { get; set; }
        public int PersonId { get; set; }
        public int ToothCount { get; set; }
        public int NormalToothCount { get; set; }
        public int BrokenToothCount { get; set; }
        public int MilkToothCount { get; set; }
        public int PermanentToothCount { get; set; }
        public string PersonDentalMonitoringDesc { get; set; }
        public string PersonDentalMonitoringZiped { get; set; }
        public int InsertUserId { get; set; }
        public System.DateTime InsertTime { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    
        public virtual Person Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonToothStatus> PersonToothStatus { get; set; }
    }
}
