//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonnelWorkshop
    {
        public int PersonnelWorkshopId { get; set; }
        public int PersonnelId { get; set; }
        public int WorkshopId { get; set; }
        public string PersonnelWorkshopDateSolar { get; set; }
        public System.DateTime PersonnelWorkshopDate { get; set; }
        public string PersonnelWorkshopDesc { get; set; }
        public string PersonnelWorkshopZiped { get; set; }
        public int InsertUserId { get; set; }
        public System.DateTime InsertTime { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    
        public virtual Personnel Personnel { get; set; }
        public virtual Workshop Workshop { get; set; }
    }
}
