//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonDamage
    {
        public int PersonDamageId { get; set; }
        public int PersonId { get; set; }
        public string PersonDamageYear { get; set; }
        public string PersonDamageMonth { get; set; }
        public string PersonDamageDay { get; set; }
        public Nullable<System.DateTime> PersonDamageDate { get; set; }
        public string PersonDamageDateSolar { get; set; }
        public int DamageCauseId { get; set; }
        public string DamageCauseDesc { get; set; }
        public int DamagedLimbId { get; set; }
        public string DamagedLimbDesc { get; set; }
        public bool HasSurgery { get; set; }
        public string SurgeryDesc { get; set; }
        public string PersonDamageZiped { get; set; }
        public int InsertUserId { get; set; }
        public System.DateTime InsertTime { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    
        public virtual DamageCause DamageCause { get; set; }
        public virtual Limb Limb { get; set; }
        public virtual Person Person { get; set; }
    }
}
