//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonJob
    {
        public int PersonJobId { get; set; }
        public int PersonId { get; set; }
        public Nullable<int> JobId { get; set; }
        public string PersonJobDesc { get; set; }
        public Nullable<decimal> PersonJobSalary { get; set; }
        public string PersonJobAddress { get; set; }
        public string PersonJobZiped { get; set; }
        public Nullable<System.DateTime> PersonJobStartDate { get; set; }
        public string PersonJobStartDateSolar { get; set; }
        public Nullable<System.DateTime> PersonJobLeaveDate { get; set; }
        public string PersonJobLeaveDateSolar { get; set; }
        public string PersonJobLeaveDesc { get; set; }
        public Nullable<System.DateTime> PersonJobFinishDate { get; set; }
        public string PersonJobFinishDateSolar { get; set; }
        public int InsertUserId { get; set; }
        public System.DateTime InsertTime { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    
        public virtual Job Job { get; set; }
        public virtual Person Person { get; set; }
    }
}
