//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonnelPursuitResult
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PersonnelPursuitResult()
        {
            this.PersonnelPursuit = new HashSet<PersonnelPursuit>();
        }
    
        public int PersonnelPursuitResultId { get; set; }
        public string PersonnelPursuitResultName { get; set; }
        public string PersonnelPursuitResultZiped { get; set; }
        public int PersonnelStatusId { get; set; }
        public int InsertUserId { get; set; }
        public System.DateTime InsertTime { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonnelPursuit> PersonnelPursuit { get; set; }
        public virtual PersonnelStatus PersonnelStatus { get; set; }
    }
}
