//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonSupportingOrganServiceType
    {
        public int PersonSupportingOrganServiceTypeId { get; set; }
        public int PersonSupportingOrganId { get; set; }
        public int ServiceTypeId { get; set; }
        public int InsertUserId { get; set; }
        public System.DateTime InsertTime { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    
        public virtual PersonSupportingOrgan PersonSupportingOrgan { get; set; }
        public virtual ServiceType ServiceType { get; set; }
    }
}
