//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonTeamGrade
    {
        public int PersonTeamGradeId { get; set; }
        public int PersonTeamId { get; set; }
        public Nullable<int> ExpertiseId { get; set; }
        public Nullable<int> BeltColorId { get; set; }
        public int DepartmentTeamCompetitionId { get; set; }
        public Nullable<int> DepartmentTeamCompetitionDetailId { get; set; }
        public int GradeId { get; set; }
        public Nullable<int> OpponentPersonId { get; set; }
        public Nullable<double> PersonPoints { get; set; }
        public Nullable<double> OpponentPersonPoints { get; set; }
        public int InsertUserId { get; set; }
        public System.DateTime InsertTime { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    
        public virtual BeltColor BeltColor { get; set; }
        public virtual DepartmentTeamCompetition DepartmentTeamCompetition { get; set; }
        public virtual DepartmentTeamCompetitionDetail DepartmentTeamCompetitionDetail { get; set; }
        public virtual Expertise Expertise { get; set; }
        public virtual Grade Grade { get; set; }
        public virtual PersonTeam PersonTeam { get; set; }
        public virtual PersonTeam PersonTeam1 { get; set; }
    }
}
