//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonSicknessType
    {
        public int PersonSicknessTypeId { get; set; }
        public int PersonId { get; set; }
        public int SicknessTypeId { get; set; }
        public string SicknessName { get; set; }
        public string SicknessEnglishName { get; set; }
        public string PersonSicknessDesc { get; set; }
        public string PersonSicknessZiped { get; set; }
        public Nullable<decimal> SicknessExpense { get; set; }
        public Nullable<System.DateTime> SicknessStartDate { get; set; }
        public string SicknessStartDateSolar { get; set; }
        public Nullable<System.DateTime> SicknessFinishDate { get; set; }
        public string SicknessFinishDateSolar { get; set; }
        public int TreatmentStatusId { get; set; }
        public bool PersonUseSpecialDrug { get; set; }
        public string DrugDesc { get; set; }
        public string MedicalAdvice { get; set; }
        public int InsertUserId { get; set; }
        public System.DateTime InsertTime { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual SicknessType SicknessType { get; set; }
        public virtual TreatmentStatus TreatmentStatus { get; set; }
    }
}
