//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonNeedType
    {
        public int PersonNeedTypeId { get; set; }
        public Nullable<int> FamilyId { get; set; }
        public int PersonId { get; set; }
        public int NeedTypeId { get; set; }
        public bool PersonNeedTypeIsFinancial { get; set; }
        public string PersonNeedTypeDesc { get; set; }
        public string PersonNeedTypeZiped { get; set; }
        public Nullable<decimal> PersonNeedTypeAmount { get; set; }
        public int InsertUserId { get; set; }
        public System.DateTime InsertTime { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    
        public virtual NeedType NeedType { get; set; }
        public virtual Person Person { get; set; }
    }
}
