//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlaceType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlaceType()
        {
            this.House = new HashSet<House>();
            this.SegmentPlaceType = new HashSet<SegmentPlaceType>();
            this.SegmentReconnaissancePlaceType = new HashSet<SegmentReconnaissancePlaceType>();
        }
    
        public int PlaceTypeId { get; set; }
        public string PlaceTypeName { get; set; }
        public string PlaceTypeDesc { get; set; }
        public string PlaceTypeZiped { get; set; }
        public bool PlaqueRequired { get; set; }
        public bool BlockRequired { get; set; }
        public bool UnitRequired { get; set; }
        public bool FloorRequired { get; set; }
        public int PlaceCategoryId { get; set; }
        public int InsertUserId { get; set; }
        public System.DateTime InsertTime { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<House> House { get; set; }
        public virtual PlaceCategory PlaceCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SegmentPlaceType> SegmentPlaceType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SegmentReconnaissancePlaceType> SegmentReconnaissancePlaceType { get; set; }
    }
}
