//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Segment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Segment()
        {
            this.AddressComponent = new HashSet<AddressComponent>();
            this.DepartmentSegment = new HashSet<DepartmentSegment>();
            this.Family = new HashSet<Family>();
            this.SegmentDrugType = new HashSet<SegmentDrugType>();
            this.SegmentEthnic = new HashSet<SegmentEthnic>();
            this.SegmentFuelType = new HashSet<SegmentFuelType>();
            this.SegmentPlaceType = new HashSet<SegmentPlaceType>();
            this.SegmentReconnaissance = new HashSet<SegmentReconnaissance>();
            this.SegmentResidentialContext = new HashSet<SegmentResidentialContext>();
            this.SegmentWaterSource = new HashSet<SegmentWaterSource>();
            this.Street = new HashSet<Street>();
        }
    
        public int SegmentId { get; set; }
        public string SegmentName { get; set; }
        public string SegmentSummaryName { get; set; }
        public string SegmentZiped { get; set; }
        public int RegionId { get; set; }
        public Nullable<int> FamilyCount { get; set; }
        public Nullable<int> PersonCount { get; set; }
        public Nullable<int> ChildrenCount { get; set; }
        public bool HasGas { get; set; }
        public bool HasPower { get; set; }
        public Nullable<int> PowerSupplyId { get; set; }
        public string PowerSupplyDesc { get; set; }
        public bool HasMobileSignal { get; set; }
        public bool HasInternetAccess { get; set; }
        public string SegmentDesc { get; set; }
        public Nullable<double> DrinkingWaterNearlyDistance { get; set; }
        public bool HasDrinkingWater { get; set; }
        public string DrinkingWaterDesc { get; set; }
        public bool SewageSystem { get; set; }
        public string SewageSystemDesc { get; set; }
        public bool WasteCollectionSystem { get; set; }
        public string WasteCollectionSystemDesc { get; set; }
        public int InsertUserId { get; set; }
        public System.DateTime InsertTime { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AddressComponent> AddressComponent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartmentSegment> DepartmentSegment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Family> Family { get; set; }
        public virtual Region Region { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SegmentDrugType> SegmentDrugType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SegmentEthnic> SegmentEthnic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SegmentFuelType> SegmentFuelType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SegmentPlaceType> SegmentPlaceType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SegmentReconnaissance> SegmentReconnaissance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SegmentResidentialContext> SegmentResidentialContext { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SegmentWaterSource> SegmentWaterSource { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Street> Street { get; set; }
    }
}
