//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SegmentReconnaissance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SegmentReconnaissance()
        {
            this.SegmentReconnaissanceDrugType = new HashSet<SegmentReconnaissanceDrugType>();
            this.SegmentReconnaissanceEthnic = new HashSet<SegmentReconnaissanceEthnic>();
            this.SegmentReconnaissanceFuelType = new HashSet<SegmentReconnaissanceFuelType>();
            this.SegmentReconnaissancePlaceType = new HashSet<SegmentReconnaissancePlaceType>();
            this.SegmentReconnaissanceResidentialContext = new HashSet<SegmentReconnaissanceResidentialContext>();
        }
    
        public int SegmentReconnaissanceId { get; set; }
        public int SegmentId { get; set; }
        public string SegmentReconnaissanceDateSolar { get; set; }
        public System.DateTime SegmentReconnaissanceDate { get; set; }
        public string SegmentReconnaissanceDesc { get; set; }
        public string SegmentReconnaissanceZiped { get; set; }
        public Nullable<int> ReconnaissanceCauseId { get; set; }
        public Nullable<int> FamilyCount { get; set; }
        public Nullable<int> PersonCount { get; set; }
        public Nullable<int> ChildrenCount { get; set; }
        public bool HasGas { get; set; }
        public bool HasPower { get; set; }
        public Nullable<int> PowerSupplyId { get; set; }
        public string PowerSupplyDesc { get; set; }
        public bool HasMobileSignal { get; set; }
        public bool HasInternetAccess { get; set; }
        public string SegmentDesc { get; set; }
        public Nullable<double> DrinkingWaterNearlyDistance { get; set; }
        public bool HasDrinkingWater { get; set; }
        public string DrinkingWaterDesc { get; set; }
        public bool SewageSystem { get; set; }
        public string SewageSystemDesc { get; set; }
        public bool WasteCollectionSystem { get; set; }
        public string WasteCollectionSystemDesc { get; set; }
        public int InsertUserId { get; set; }
        public System.DateTime InsertTime { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    
        public virtual PowerSupply PowerSupply { get; set; }
        public virtual ReconnaissanceCause ReconnaissanceCause { get; set; }
        public virtual Segment Segment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SegmentReconnaissanceDrugType> SegmentReconnaissanceDrugType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SegmentReconnaissanceEthnic> SegmentReconnaissanceEthnic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SegmentReconnaissanceFuelType> SegmentReconnaissanceFuelType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SegmentReconnaissancePlaceType> SegmentReconnaissancePlaceType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SegmentReconnaissanceResidentialContext> SegmentReconnaissanceResidentialContext { get; set; }
    }
}
