//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkillTypeAgeRange
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SkillTypeAgeRange()
        {
            this.CompetitionSkillTypeAgeRange = new HashSet<CompetitionSkillTypeAgeRange>();
            this.Team = new HashSet<Team>();
        }
    
        public int SkillTypeAgeRangeId { get; set; }
        public int SkillTypeId { get; set; }
        public string SkillTypeAgeRangeName { get; set; }
        public Nullable<int> AgeRangeMin { get; set; }
        public Nullable<int> AgeRangeMax { get; set; }
        public string SkillTypeZiped { get; set; }
        public int InsertUserId { get; set; }
        public System.DateTime InsertTime { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompetitionSkillTypeAgeRange> CompetitionSkillTypeAgeRange { get; set; }
        public virtual SkillType SkillType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Team> Team { get; set; }
    }
}
