//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubSystem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubSystem()
        {
            this.Feature = new HashSet<Feature>();
            this.Feature1 = new HashSet<Feature>();
            this.SubSystem1 = new HashSet<SubSystem>();
        }
    
        public int SubSystemId { get; set; }
        public string SubSystemName { get; set; }
        public string ControlName { get; set; }
        public string SubSystemIconCss { get; set; }
        public bool SubSystemIsActive { get; set; }
        public Nullable<int> SubSystemIndex { get; set; }
        public bool SubSystemLoadGrid { get; set; }
        public string ReportGroupBy { get; set; }
        public string DimensionX { get; set; }
        public string DimensionY { get; set; }
        public string DimensionXFa { get; set; }
        public string DimensionYFa { get; set; }
        public string SubSystemUserGuidePath { get; set; }
        public string SubSystemActionOnLoad { get; set; }
        public string SubSystemActionOnInsert { get; set; }
        public string SubSystemActionOnEdit { get; set; }
        public string SubSystemZiped { get; set; }
        public Nullable<int> ParentId { get; set; }
        public int InsertUserId { get; set; }
        public System.DateTime InsertTime { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Feature> Feature { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Feature> Feature1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubSystem> SubSystem1 { get; set; }
        public virtual SubSystem SubSystem2 { get; set; }
    }
}
