//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Counties
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Counties()
        {
            this.tbl_Villages = new HashSet<tbl_Villages>();
            this.tbl_Zones = new HashSet<tbl_Zones>();
        }
    
        public int CountyId { get; set; }
        public int CityId { get; set; }
        public string Name { get; set; }
        public Nullable<double> X { get; set; }
        public Nullable<double> Y { get; set; }
    
        public virtual tbl_Cities tbl_Cities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Villages> tbl_Villages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Zones> tbl_Zones { get; set; }
    }
}
