//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Zones
    {
        public int ZoneId { get; set; }
        public Nullable<int> VillageId { get; set; }
        public string Name { get; set; }
        public Nullable<int> CountyId { get; set; }
        public Nullable<double> X { get; set; }
        public Nullable<double> Y { get; set; }
    
        public virtual tbl_Counties tbl_Counties { get; set; }
        public virtual tbl_Villages tbl_Villages { get; set; }
    }
}
