//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Team()
        {
            this.DepartmentTeam = new HashSet<DepartmentTeam>();
            this.TeamRequiredGoods = new HashSet<TeamRequiredGoods>();
        }
    
        public int TeamId { get; set; }
        public int SkillTypeId { get; set; }
        public Nullable<int> SkillTypeAgeRangeId { get; set; }
        public string TeamName { get; set; }
        public string TeamSummaryName { get; set; }
        public string TeamZiped { get; set; }
        public Nullable<int> GenderId { get; set; }
        public Nullable<int> SkillTypeMethod { get; set; }
        public int InsertUserId { get; set; }
        public System.DateTime InsertTime { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartmentTeam> DepartmentTeam { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual SkillType SkillType { get; set; }
        public virtual SkillType SkillType1 { get; set; }
        public virtual SkillTypeAgeRange SkillTypeAgeRange { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeamRequiredGoods> TeamRequiredGoods { get; set; }
    }
}
