//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workspace
    {
        public int WorkspaceId { get; set; }
        public string WorkspaceName { get; set; }
        public string WorkspaceSummaryName { get; set; }
        public string WorkspaceZiped { get; set; }
        public string WorkspaceUsername { get; set; }
        public string WorkspacePassword { get; set; }
        public string WorkspaceCompany { get; set; }
        public string WorkspaceUrl { get; set; }
        public string WorkspaceNumber { get; set; }
        public int InsertUserId { get; set; }
        public System.DateTime InsertTime { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
    }
}
