//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workshop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Workshop()
        {
            this.PersonnelWorkshop = new HashSet<PersonnelWorkshop>();
            this.PersonWorkshop = new HashSet<PersonWorkshop>();
            this.Workshop1 = new HashSet<Workshop>();
        }
    
        public int WorkshopId { get; set; }
        public string WorkshopName { get; set; }
        public string WorkshopDesc { get; set; }
        public string WorkshopZiped { get; set; }
        public bool WorkshopForPersonnel { get; set; }
        public bool WorkshopForChild { get; set; }
        public bool WorkshopForMothers { get; set; }
        public bool WorkshopForBoys { get; set; }
        public bool WorkshopForGirls { get; set; }
        public bool WorkshopForFathers { get; set; }
        public Nullable<int> WorkshopPrerequisiteId { get; set; }
        public int InsertUserId { get; set; }
        public System.DateTime InsertTime { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonnelWorkshop> PersonnelWorkshop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonWorkshop> PersonWorkshop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Workshop> Workshop1 { get; set; }
        public virtual Workshop Workshop2 { get; set; }
    }
}
