namespace IASData.Enumerable
{
    public enum Controllers
    {
        Default,
        SubSystem,
        UserInfo,
        volunteer,
        EducationYear,
        Course,
        AccessLevel,
        Job,
        JobStatus,
        Person,
        PersonSearch,
        EducationYearClassMember,
        EducationYearClassCourseHistory,
        EducationYearClassMemberHistory,
        SkillType,
        Role,
        Province,
        City,
        Region,
        Segment,
        Department,
        Street,
        Alley,
    }
}